/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'SendWelcomeEmail': EventHandler<{ userId?: string; email?: string; name?: string }, never>
    'HealthCheck': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { status: string; timestamp: string }> | ApiResponse<500, { error: string }>, never>
    'RegisterUser': ApiRouteHandler<{ email: string; password: string; name: string; isAdmin?: boolean }, ApiResponse<200, { message: string; accessToken: string; refreshToken: string; user: { id: string; email: string } }> | ApiResponse<400, { error: string }> | ApiResponse<409, { error: string }>, { topic: 'send-welcome-email'; data: { userId?: string; email?: string; name?: string } }>
    'RefreshToken': ApiRouteHandler<{ refreshToken: string }, ApiResponse<200, { accessToken: string; refreshToken: string }> | ApiResponse<401, { error: string }>, never>
    'GetCurrentUser': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { user: { id: string; email: string; name: string; avatar?: string; isAdmin: boolean } }> | ApiResponse<401, { error: string }>, never>
    'LogoutUser': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string }>, never>
    'LoginUser': ApiRouteHandler<{ email: string; password: string }, ApiResponse<200, { email: string; refreshToken: string; accessToken: string; user: { id: string; email: string } }> | ApiResponse<401, { error: string }>, never>
    'GoogleOAuth': ApiRouteHandler<{ idToken: string }, ApiResponse<200, { message: string; email: string; refreshToken: string; accessToken: string; user: { id: string; email: string; name: string; avatar?: string } }> | ApiResponse<401, { error: string }>, { topic: 'send-welcome-email'; data: { userId?: string; email?: string; name?: string } }>
  }
    
}