/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'SendWelcomeEmail': EventHandler<{ userId?: string; email?: string; name?: string }, never>
    'RegisterUser': ApiRouteHandler<{ email: string; password: string; name: string; isAdmin?: boolean }, ApiResponse<200, { message: string; accessToken: string; refreshToken: string; user: { id: string; email: string } }> | ApiResponse<400, { error: string }> | ApiResponse<409, { error: string }>, { topic: 'send-welcome-email'; data: { userId?: string; email?: string; name?: string } }>
    'LoginUser': ApiRouteHandler<{ email: string; password: string }, ApiResponse<200, { email: string; refreshToken: string; accessToken: string; user: { id: string; email: string } }> | ApiResponse<401, { error: string }>, never>
  }
    
}